import c4d


DiffuseName = "Diffuse"
GlossyName = "Glossy"
SpecularName = "Specular"
UniversalName = "Universal"
MetallicName = "Metallic"
ToonName = "Toon"

SUBMaterialNodeID = 1040369


SET_RENDERAOV_IN_CNT=3700
SET_RENDERAOV_INPUT_0=3740

ID_OCTANE_VIDEO_POST = 1029525 # octane render
ID_OCTANE_RENDERPASS_AOV = 1057006 # pass
VP_BUFFER_TYPE      = 1010
VP_COLOR_SPACE      = 1028
# RenderPassAOV_h
RNDAOV_NAME=900
RNDAOV_ENABLED=994
RNDAOV_TYPE=995
RNDAOV_TYPE_NAME=1101

RNDAOV_DIFFUSE=188
RNDAOV_DIF_FILTER=191
RNDAOV_REFLECTION=222
RNDAOV_REFL_FILTER=225
RNDAOV_REFRACT_FILTER=230
RNDAOV_TRANSM_FILTER=242
RNDAOV_TEX_TANGENT=240
RNDAOV_UVSET=3459
RNDAOV_CRYPTOMATTE=185

RNDAOV_EMIT=196
RNDAOV_ENV=197
RNDAOV_DIF_D=189
RNDAOV_DIF_I=193
RNDAOV_REFL_D=223
RNDAOV_REFL_I=227
RNDAOV_REFRACT=229
RNDAOV_TRANS=244
RNDAOV_SSS=238
RNDAOV_POST=221
RNDAOV_NOISE=212
RNDAOV_SHADOW=237
RNDAOV_LAYER_BLACKSHD=202
RNDAOV_LAYER_COLORSHD=204
RNDAOV_LAYER_REFLECTION=203

RNDAOV_POST_INCLUDE_ENV=3325
RNDAOV_IRRADIANCE=201
RNDAOV_LIGHT_DIRECTION=207
RNDAOV_VOLUME=246
RNDAOV_VOLUME_MASK=250
RNDAOV_VOLUME_EMISSION=248
RNDAOV_VOLUME_Z_DEPTH_FRONT=251
RNDAOV_VOLUME_Z_DEPTH_BACK=252
RNDAOV_CUSTOM=186
RNDAOV_GLOBALTEX=199
RNDAOV_CUSTOM_IDS=3390
RNDAOV_VISIBLE_AFTER=3391
RNDAOV_ZDEPTH_MAX=3392
RNDAOV_ZDEPTH_ENVDEPTH=3397
RNDAOV_UVMAX=3393
RNDAOV_MAXSPEED=3394
RNDAOV_AODIST=3395
RNDAOV_AOALPHASHD=3396
RNDAOV_WIRE_SHADING=3398
RNDAOV_WIRE_BMPNRML_MAP=3399
RNDAOV_WIRE_HGLTBACK=3400

RNDAOV_GEONORM=198
RNDAOV_SHDNORM=236
RNDAOV_SMOOTHNORM=253
RNDAOV_POSITION=220
RNDAOV_ZDEPTH=255
RNDAOV_MATID=210
RNDAOV_UV_COORD=245
RNDAOV_TANGENT=239
RNDAOV_WIRE=254
RNDAOV_OBJECT_ID=217
RNDAOV_AO=183
RNDAOV_MOTION_VECTOR=211
RNDAOV_RENDER_LAYER_ID=233
RNDAOV_RENDER_LAYER_MASK=234
RNDAOV_FSIZE=3347
RNDAOV_LIGHT_PASS_ID=209
RNDAOV_OBJECT_LAYER_COLOR=218
RNDAOV_BAKEGROUP_ID=184
RNDAOV_SMOOTHNORM_N=3442
RNDAOV_TANGENT_N=3446
RNDAOV_GEONORM_N=3440
RNDAOV_SHDNORM_N=3441
RNDAOV_POSITION_N=3443
RNDAOV_ZDEPTH_N=3444
RNDAOV_UV_COORD_N=3445
RNDAOV_MOT_VECTOR_N=3447
RNDAOV_TEX_TANGENT_N=3448

RNDAOV_DISTR_PT=3350
RNDAOV_DIST_TRACING=3351
RNDAOV_BEAUTY_DENOISER=3380
RNDAOV_DENOISER_DIFFUSE_D=190
RNDAOV_DENOISER_DIFFUSE_I=194
RNDAOV_DENOISER_REFLECT_D=224
RNDAOV_DENOISER_REFLECT_I=228
RNDAOV_DENOISER_REFRACTION=3385
RNDAOV_DENOISER_REMAINDER=232
RNDAOV_DENOISER_EMISSION=195
RNDAOV_DENOISER_VOLUME=247
RNDAOV_DENOISER_VOL_EMIS=249

RNDAOV_INFO_OPACITY=219
RNDAOV_INFO_ROUGHNESS=235
RNDAOV_INFO_DIFFUSE=192
RNDAOV_INFO_REFLECTION=3364
RNDAOV_INFO_REFL_FILTER=226
RNDAOV_INFO_REFRACTION=3365
RNDAOV_INFO_REFRACT_FILTER=231
RNDAOV_INFO_IOR=200
RNDAOV_INFO_TRANSMISSON=243
RNDAOV_RAW=3450
RNDAOV_LIGHT=205
RNDAOV_LIGHT_D=206
RNDAOV_LIGHT_I=208
RNDAOV_CRYPTO_TYPE=1821
RNDAOV_LIGHT_ID=1822

ID_OCTANE_BASE_MATERIAL = 1029501
ID_OCTANE_STANDARD_SURFACE = 1058763
ID_OCTANE_COMPOSITE_MATERIAL = 1040075
ID_OCTANE_MIX_MATERIAL = 1029622
ID_OCTANE_PORTAL_MATERIAL = 1029623
ID_OCTANE_CLIPPING_MATERIAL = 1056989
ID_OCTANE_SHADOWCATCHER_MAT = 1057003
ID_OCTANE_HAIR_MATERIAL = 1054119
OCTANE_MATERIALS = [ID_OCTANE_BASE_MATERIAL,
                    ID_OCTANE_STANDARD_SURFACE,
                    ID_OCTANE_MIX_MATERIAL,
                    ID_OCTANE_PORTAL_MATERIAL,
                    ID_OCTANE_CLIPPING_MATERIAL,
                    ID_OCTANE_SHADOWCATCHER_MAT,
                    ID_OCTANE_HAIR_MATERIAL,
                    ID_OCTANE_COMPOSITE_MATERIAL
                    ]


MAT_TYPE_DIFFUSE = 2510
MAT_TYPE_GLOSSY = 2511
MAT_TYPE_SPECULAR = 2513
MAT_TYPE_METALLIC = 2514
MAT_TYPE_TOON = 2515
MAT_TYPE_UNIVERSAL = 2516

BRDF_OCTANE = 0
BRDF_GGX = 2
BRDF_GGX_EP = 6

# Node IDs for Octane nodes
ID_OCTANE_FLOAT_TEXTURE = 1029506
ID_OCTANE_IMAGE_TEXTURE = 1029508
ID_OCTANE_RGBSPECTRUM = 1029504

ID_OCTANE_MULTIPLY_TEXTURE = 1029516
ID_OCTANE_SUBTRACT_TEXTURE = 1038878
ID_OCTANE_INVERT_TEXTURE = 1029514
ID_OCTANE_ADD_TEXTURE = 1038877
ID_OCTANE_MIXTEXTURE = 1029505

ID_OCTANE_COLORCORRECTION = 1029512
ID_OCTANE_GRADIENT_TEXTURE = 1029513
ID_OCTANE_CLAMP_TEXTURE = 1029511
ID_INSTANCE_RANGE_TEXTURE = 1039376
ID_OCTANE_FALLOFFMAP = 1029503
ID_OCTANE_DIRT_TEXTURE = 1029975
ID_OCTANE_CURVATURE_TEX = 1057004
ID_OCTANE_C4DNOISE_TEX = 1058853
ID_OCTANE_NOISE_TEXTURE = 1033698

ID_OCTANE_TRIPLANAR = 1038882
ID_OCTANE_TRANSFORM = 1030961
ID_OCTANE_DISPLACEMENT = 1031901
ID_OCTANE_TEXTURE_PROJECTION = 1031460
ID_OCTANE_BLACKBODY_EMISSION = 1029641
ID_OCTANE_TEXTURE_EMISSION = 1029642

ID_OCTANE_LIVEPLUGIN = 1029499 # Octane Live Viewer
ID_OCTANE_CAMERATAG = 1029524 # Octane Camera Tag
ID_OCTANE_ENVIRONMENT_TAG = 1029643
ID_OCTANE_OBJECTTAG = 1029603
ID_OCTANE_LIGHT_TAG = 1029526

ID_VOLUMEOBJECT = 1035792
ID_SCATTER_OBJECT = 1035961
ID_OCTANE_DAYLIGHT_TAG = 1029754

AOV_SYMBOLS: dict[int, str] = {
 RNDAOV_AO: 'Ao',
 RNDAOV_AOALPHASHD: 'Ao alpha shadow',
 RNDAOV_AODIST: 'Aodist',
 RNDAOV_BAKEGROUP_ID: 'Bakegroup Id',
 RNDAOV_BEAUTY_DENOISER: 'Beauty Denoiser',
 RNDAOV_CRYPTOMATTE: 'Cryptomatte',
 RNDAOV_CUSTOM: 'Custom',
 RNDAOV_CUSTOM_IDS: 'Custom Ids',
 RNDAOV_DENOISER_DIFFUSE_D: 'Denoiser diffuse direct',
 RNDAOV_DENOISER_DIFFUSE_I: 'Denoiser Diffuse indirect',
 RNDAOV_DENOISER_EMISSION: 'Denoiser Emission',
 RNDAOV_DENOISER_REFLECT_D: 'Denoiser Reflect direct',
 RNDAOV_DENOISER_REFLECT_I: 'Denoiser Reflect indirect',
 RNDAOV_DENOISER_REFRACTION: 'Denoiser Refraction',
 RNDAOV_DENOISER_REMAINDER: 'Denoiser Remainder',
 RNDAOV_DENOISER_VOLUME: 'Denoiser Volume',
 RNDAOV_DENOISER_VOL_EMIS: 'Denoiser Vol Emission',
 RNDAOV_DIFFUSE: 'Diffuse',
 RNDAOV_DIF_D: 'Diffuse direct',
 RNDAOV_DIF_FILTER: 'Diffuse Filter',
 RNDAOV_DIF_I: 'Diffuse indirect',
 RNDAOV_DISTR_PT: 'Distr Pt',
 RNDAOV_DIST_TRACING: 'Dist Tracing',
 RNDAOV_EMIT: 'Emit',
 RNDAOV_ENV: 'Env',
 RNDAOV_FSIZE: 'Fsize',
 RNDAOV_GEONORM: 'Geo normal',
 RNDAOV_GEONORM_N: 'Geonorm N',
 RNDAOV_GLOBALTEX: 'Globaltex',
 RNDAOV_INFO_DIFFUSE: 'Info Diffuse',
 RNDAOV_INFO_IOR: 'Info Ior',
 RNDAOV_INFO_OPACITY: 'Info Opacity',
 RNDAOV_INFO_REFLECTION: 'Info Reflection',
 RNDAOV_INFO_REFL_FILTER: 'Info Refl Filter',
 RNDAOV_INFO_REFRACTION: 'Info Refraction',
 RNDAOV_INFO_REFRACT_FILTER: 'Info Refract Filter',
 RNDAOV_INFO_ROUGHNESS: 'Info Roughness',
 RNDAOV_INFO_TRANSMISSON: 'Info Transmisson',
 RNDAOV_IRRADIANCE: 'Irradiance',
 RNDAOV_LAYER_BLACKSHD: 'Layer Blackshd',
 RNDAOV_LAYER_COLORSHD: 'Layer Colorshd',
 RNDAOV_LAYER_REFLECTION: 'Layer Reflection',
 RNDAOV_LIGHT: 'Light',
 RNDAOV_LIGHT_D: 'Light direct',
 RNDAOV_LIGHT_DIRECTION: 'Light Direction',
 RNDAOV_LIGHT_I: 'Light indirect',
 RNDAOV_LIGHT_PASS_ID: 'Light Pass Id',
 RNDAOV_MATID: 'Material id',
 RNDAOV_MAXSPEED: 'Maxspeed',
 RNDAOV_MOTION_VECTOR: 'Motion Vector',
 RNDAOV_MOT_VECTOR_N: 'Mot Vector N',
 RNDAOV_NOISE: 'Noise',
 RNDAOV_OBJECT_ID: 'Object Id',
 RNDAOV_OBJECT_LAYER_COLOR: 'Object Layer Color',
 RNDAOV_POSITION: 'Position',
 RNDAOV_POSITION_N: 'Position N',
 RNDAOV_POST: 'Post',
 RNDAOV_POST_INCLUDE_ENV: 'Post Include Env',
 RNDAOV_RAW: 'Raw',
 RNDAOV_REFLECTION: 'Reflection',
 RNDAOV_REFL_D: 'Refl direct',
 RNDAOV_REFL_FILTER: 'Refl Filter',
 RNDAOV_REFL_I: 'Refl indirect',
 RNDAOV_REFRACT: 'Refract',
 RNDAOV_REFRACT_FILTER: 'Refract Filter',
 RNDAOV_RENDER_LAYER_ID: 'Render Layer Id',
 RNDAOV_RENDER_LAYER_MASK: 'Render Layer Mask',
 RNDAOV_SHADOW: 'Shadow',
 RNDAOV_SHDNORM: 'Shdnorm',
 RNDAOV_SHDNORM_N: 'Shdnorm N',
 RNDAOV_SMOOTHNORM: 'Smoothnorm',
 RNDAOV_SMOOTHNORM_N: 'Smoothnorm N',
 RNDAOV_SSS: 'SSS',
 RNDAOV_TANGENT: 'Tangent',
 RNDAOV_TANGENT_N: 'Tangent N',
 RNDAOV_TEX_TANGENT: 'Tex Tangent',
 RNDAOV_TEX_TANGENT_N: 'Tex Tangent N',
 RNDAOV_TRANS: 'Trans',
 RNDAOV_TRANSM_FILTER: 'Transm Filter',
 RNDAOV_UVMAX: 'Uvmax',
 RNDAOV_UVSET: 'Uvset',
 RNDAOV_UV_COORD: 'Uv Coord',
 RNDAOV_UV_COORD_N: 'Uv Coord N',
 RNDAOV_VISIBLE_AFTER: 'Visible After',
 RNDAOV_VOLUME: 'Volume',
 RNDAOV_VOLUME_EMISSION: 'Volume Emission',
 RNDAOV_VOLUME_MASK: 'Volume Mask',
 RNDAOV_VOLUME_Z_DEPTH_BACK: 'Volume Z Depth Back',
 RNDAOV_VOLUME_Z_DEPTH_FRONT: 'Volume Z Depth Front',
 RNDAOV_WIRE: 'Wire',
 RNDAOV_WIRE_BMPNRML_MAP: 'Wire Bmpnrml Map',
 RNDAOV_WIRE_HGLTBACK: 'Wire Hgltback',
 RNDAOV_WIRE_SHADING: 'Wire Shading',
 RNDAOV_ZDEPTH: 'Zdepth',
 RNDAOV_ZDEPTH_ENVDEPTH: 'Zdepth Envdepth',
 RNDAOV_ZDEPTH_MAX: 'Zdepth Max',
 RNDAOV_ZDEPTH_N: 'Zdepth Normal'
 }

CAMERA_TYPE = 1439
CAM_TYPE_UNIVERSIAL = 5
CAM_UNIVERSIAL_APERTURESHAPE = 1515
CAM_APERTURE_CUSTOM = 4
CAM_APERTURE_TEXTURE = 1507

MAT_NAME_SYMBOLS: dict[int, str]  = {
    ID_OCTANE_STANDARD_SURFACE: "Standard Surface",
    ID_OCTANE_COMPOSITE_MATERIAL: "Composite Material",
    MAT_TYPE_SPECULAR: "Specular",
    MAT_TYPE_DIFFUSE: "Diffuse",
    MAT_TYPE_GLOSSY: "Glossy",
    MAT_TYPE_METALLIC: "Metalc",
    MAT_TYPE_UNIVERSAL: "Universal",
    MAT_TYPE_TOON: "Toon"

}

ID_ORBX_LOADER: int = 1050418